### ISSUE TITLE
Why randomize the phase?

### ISSUE THREAD

**Issue by Cortexelus** [paulnasca/paulstretch_python#3]
Why randomize the phase? It makes everything sound super reverberant. Although I do enjoy it, and I must say it has become the signature paulstretch sound. 

However, you get a cleaner extreme time stretch if you interpolate the _change in phase from frame to frame_. Interpolating phase itself won't produce meaningful results, and I know I was led astray initially by trying this, but interpolating the change in phase may sound more natural.

Check it out:
https://www.youtube.com/watch?v=h5SObE8JSX8
Read all about the technique here:
http://www.mitpressjournals.org/doi/pdf/10.1162/comj.2008.32.3.87

**Comment by paulnasca** [comment]
Hi.
One reason I randomize the phase is that the resulted sound is more soft (more pleasant to listen many hours continuously) and also the algorithm is much simpler even if I sacrifice the transients. Even more, usualy I recomand using Paulstretch with larger windows (more than half a second) resulting subjectively very pleasant sound texture. 
Many years ago I tried myself, too, using phase differences and other ways to interpolate the phases, but I didn't liked the results.

Another reason is that phase randomization models very good for ensemble sounds (like choirs, orchestras). I described more about it on ZynAddSubFX page: http://zynaddsubfx.sourceforge.net/doc_0.html 

Anyway, the "paulstretch_newmethod.py" it have an onset detection which changes the speed on onsets but I sill like more how the "paulstretch_stereo.py" sounds (the original algorithm).

For the video you gave me, indeed, it is very accurate stretch (more accurate than Paulstretch could do in relation to the transients), but do you have an choir processed with the same algorithm? I am curious how it sounds on this ( http://hypermammut.sourceforge.net/paulstretch/original.ogg ), for example, at 20x stretch.
Thanks.

Paul
