### ISSUE TITLE
Inputting filename from command line?

### ISSUE THREAD

**Issue by synchronometry** [paulnasca/paulstretch_python#4]
Using python3, I cannot seem to use any of the argparse options or input a wav file. Can you give an example command-line syntax in the readme? I receive the same error trying to access the -help arg as well.

python3 paulstretch_newmethod.py TTLS.wav
print "Error loading wav: "+filename

**Comment by paulnasca** [comment]
The reason of this error is the incompatibility of the 'print' statement with python3. I solved this issue in the latest version.
